name: workflow-prerelease

on:
  release:
    types: [prereleased]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: action/checkout@v1
    
    - name: 'Execute command'
      run: ls